### PR TITLE
Update strings.txt

### PR DESCRIPTION
**Pull request by Blackfiction**

### CODE REVIEW

**Comment by michaelherger** [comment]
Thanks!

**Comment by Blackfiction** [comment]
> Thanks!

One question; if I open Spotify plugin in LMS it shows a string called 'Popular Playlists' -> where can I translate that one?

**Comment by michaelherger** [comment]
Some of those strings come with the data from Spotify. You can check this on open.spotify.com's landing page.

**Comment by Blackfiction** [comment]
Don’t see it on the landing page…
Changed my settings to Dutch and still showing popular playlists…

**Comment by michaelherger** [comment]
Hmm... they've changed their web site again... This is an undocumented call I'm using to get the "Home" items. It used to be https://api.spotify.com/v1/views/desktop-home (with a token). But that's no longer used in the web UI. You could enable debug logging for plugin.spotty to see all the raw data received. I believe you should find that string in there.

**Pull request merged**
